maj gradle

diff --git a/.github/workflows/Release.yml b/.github/workflows/Release.yml
--- a/.github/workflows/Release.yml
+++ b/.github/workflows/Release.yml
@@ -70,12 +70,20 @@ jobs:
          fi
          echo "FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}"
 
+      # Vérification de l'existence du fichier APK
+      - name: Check if APK exists
+        run: |
+         if [ ! -f "app/build/outputs/apk/release/app-release.apk" ]; then
+         echo "APK not found, please check your build process" && exit 1
+         fi
+         echo "APK found: app/build/outputs/apk/release/app-release.apk"
+
       # Déploiement sur Firebase App Distribution
       - name: Upload to Firebase App Distribution
         uses: wzieba/Firebase-Distribution-Github-Action@v1
         with:
           appId: ${{ secrets.FIREBASE_APP_ID }}   # Firebase Application ID
-          groups: testers                         # Firebase group defined for testers
+          groups: julien.seguin@hotmail.fr                         # Firebase group defined for testers
           file: app/build/outputs/apk/release/app-release.apk  # Path to the generated APK
           serviceCredentialsFileContent: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}  # Firebase service account JSON key
         env:
